ism = input("ismingiz nima? ")
print("salom ",ism)
son1 = int(input("ixtiyoriy son ayting "))
son2 = int(input("ixtiyoriy ikkinchi sonni ayting "))
print("yigindisi", son1 + son2)
print("ayirmasi", son1 - son2)
print("kopaytmasi", son1 * son2)
print("bolinmasi", son1 / son2)
print(ism,"hisoblash tugadi")
